---
- hosts: node2
  strategy: free
  gather_facts: true
  become: true
  tasks:
  - name: Setting Hostname
    command: hostnamectl set-hostname node2.test.example.com
  - name: Creating Ansible User
    user:
      name: user
      shell: /bin/bash
      groups: wheel
      append: yes
  - name: Changing User Password
    shell: echo password | sudo passwd user --stdin
  - name: Fixing hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.0\.1'
      state: absent
  - name: Rebuilding host file
    lineinfile:
      path: /etc/hosts
      line: 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      create: yes
  - name: Adding control address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.60 control.test.example.com control
      create: yes
  - name: Adding Repo address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.59 repo.test.example.com repo
      create: yes
  - name: Adding node1 IP address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.61 node1.test.example.com node1
      create: yes
  - name: Adding node2 IP address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.62 node2.test.example.com node2
      create: yes
  - name: Configuring network
    command: nmcli con mod "System eth0" ipv4.addresses 192.168.55.62/24 ipv4.gateway 192.168.55.1 ipv4.dns 8.8.8.8 ipv4.method manual
  - name: Restarting Network
    command: nmcli con up "System eth0" 
  - name: Generating RSA Key
    command : ssh-keygen -q -t rsa -f /etc/ssh/ssh_host_rsa_key -C "" -N ""
    args:
      creates: /etc/ssh/ssh_host_rsa_key
  - name: Fixing Resolv File
    shell: echo 'nameserver 8.8.8.8' > /etc/resolv.conf
  - name: Enabling services
    service: name=firewalld enabled=true
  - name: Starting services
    service: name=firewalld state=started
    tags: repo
  - name: Creating Welcome Message
    file:
      path: /etc/profile.d/welcome.sh
      state: touch
      mode: 0755
  - name: Building Welcome Message
    blockinfile:
      dest: /etc/profile.d/welcome.sh
      block: |
         #!/bin/bash
         #
         echo -e '       
         #           _            _           _           _        _       
         #          /\ \     _   /\ \        /\ \        /\ \    /\ \      
         #         /  \ \   /\_\/  \ \      /  \ \____  /  \ \  /  \ \     
         #        / /\ \ \_/ / / /\ \ \    / /\ \_____\/ /\ \ \/ /\ \ \    
         #       / / /\ \___/ / / /\ \ \  / / /\/___  / / /\ \_\/_/\ \ \   
         #      / / /  \/____/ / /  \ \_\/ / /   / / / /_/_ \/_/   / / /   
         #     / / /    / / / / /   / / / / /   / / / /____/\     / / /    
         #    / / /    / / / / /   / / / / /   / / / /\____\/    / / /  _  
         #   / / /    / / / / /___/ / /\ \ \__/ / / / /______   / / /_/\_\ 
         #  / / /    / / / / /____\/ /  \ \___\/ / / /_______\ / /_____/ / 
         #  \/_/     \/_/\/_________/    \/_____/\/__________/ \________/  
         '"#
         #
         # You are logged into \"`hostname`\" as user \"`whoami`\"
         # This system is running `cat /etc/redhat-release`
         # kernel is `uname -r`
         #
         "
...